// Generated by gencpp from file locobot_control/JointCommandResponse.msg
// DO NOT EDIT!


#ifndef LOCOBOT_CONTROL_MESSAGE_JOINTCOMMANDRESPONSE_H
#define LOCOBOT_CONTROL_MESSAGE_JOINTCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace locobot_control
{
template <class ContainerAllocator>
struct JointCommandResponse_
{
  typedef JointCommandResponse_<ContainerAllocator> Type;

  JointCommandResponse_()
    : result(false)  {
    }
  JointCommandResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::locobot_control::JointCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::locobot_control::JointCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointCommandResponse_

typedef ::locobot_control::JointCommandResponse_<std::allocator<void> > JointCommandResponse;

typedef boost::shared_ptr< ::locobot_control::JointCommandResponse > JointCommandResponsePtr;
typedef boost::shared_ptr< ::locobot_control::JointCommandResponse const> JointCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::locobot_control::JointCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::locobot_control::JointCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace locobot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'HasHeader': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::locobot_control::JointCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::locobot_control::JointCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::locobot_control::JointCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::locobot_control::JointCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "locobot_control/JointCommandResponse";
  }

  static const char* value(const ::locobot_control::JointCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
";
  }

  static const char* value(const ::locobot_control::JointCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::locobot_control::JointCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::locobot_control::JointCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCOBOT_CONTROL_MESSAGE_JOINTCOMMANDRESPONSE_H
