// Generated by gencpp from file orb_slam2_ros/Traj.msg
// DO NOT EDIT!


#ifndef ORB_SLAM2_ROS_MESSAGE_TRAJ_H
#define ORB_SLAM2_ROS_MESSAGE_TRAJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace orb_slam2_ros
{
template <class ContainerAllocator>
struct Traj_
{
  typedef Traj_<ContainerAllocator> Type;

  Traj_()
    : header()
    , poses()
    , mnIds()  {
    }
  Traj_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)
    , mnIds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _mnIds_type;
  _mnIds_type mnIds;





  typedef boost::shared_ptr< ::orb_slam2_ros::Traj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orb_slam2_ros::Traj_<ContainerAllocator> const> ConstPtr;

}; // struct Traj_

typedef ::orb_slam2_ros::Traj_<std::allocator<void> > Traj;

typedef boost::shared_ptr< ::orb_slam2_ros::Traj > TrajPtr;
typedef boost::shared_ptr< ::orb_slam2_ros::Traj const> TrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orb_slam2_ros::Traj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orb_slam2_ros::Traj_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace orb_slam2_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'HasHeader': True, 'IsMessage': True}
// {'orb_slam2_ros': ['/home/developer/low_cost_ws/src/pyrobot/robots/LoCoBot/locobot_navigation/orb_slam2_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2_ros::Traj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2_ros::Traj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2_ros::Traj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2_ros::Traj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam2_ros::Traj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam2_ros::Traj_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orb_slam2_ros::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5880ce1007ffb54f9d4910dd5b0777b0";
  }

  static const char* value(const ::orb_slam2_ros::Traj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5880ce1007ffb54fULL;
  static const uint64_t static_value2 = 0x9d4910dd5b0777b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::orb_slam2_ros::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orb_slam2_ros/Traj";
  }

  static const char* value(const ::orb_slam2_ros::Traj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orb_slam2_ros::Traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
geometry_msgs/Pose[] poses\n\
uint32[] mnIds\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::orb_slam2_ros::Traj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orb_slam2_ros::Traj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
      stream.next(m.mnIds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Traj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orb_slam2_ros::Traj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orb_slam2_ros::Traj_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "mnIds[]" << std::endl;
    for (size_t i = 0; i < v.mnIds.size(); ++i)
    {
      s << indent << "  mnIds[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.mnIds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_ROS_MESSAGE_TRAJ_H
