// Generated by gencpp from file pyrobot_bridge/FkCommandRequest.msg
// DO NOT EDIT!


#ifndef PYROBOT_BRIDGE_MESSAGE_FKCOMMANDREQUEST_H
#define PYROBOT_BRIDGE_MESSAGE_FKCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pyrobot_bridge
{
template <class ContainerAllocator>
struct FkCommandRequest_
{
  typedef FkCommandRequest_<ContainerAllocator> Type;

  FkCommandRequest_()
    : joint_angles()
    , end_frame()  {
    }
  FkCommandRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)
    , end_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _end_frame_type;
  _end_frame_type end_frame;





  typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FkCommandRequest_

typedef ::pyrobot_bridge::FkCommandRequest_<std::allocator<void> > FkCommandRequest;

typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandRequest > FkCommandRequestPtr;
typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandRequest const> FkCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pyrobot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'HasHeader': False, 'IsFixedSize': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b8f600845f229eef0af25925836b63";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b8f600845f229eULL;
  static const uint64_t static_value2 = 0xef0af25925836b63ULL;
};

template<class ContainerAllocator>
struct DataType< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyrobot_bridge/FkCommandRequest";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64[] joint_angles\n\
string end_frame\n\
\n\
";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
      stream.next(m.end_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FkCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyrobot_bridge::FkCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
    s << indent << "end_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.end_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYROBOT_BRIDGE_MESSAGE_FKCOMMANDREQUEST_H
