// Generated by gencpp from file pyrobot_bridge/FkCommandResponse.msg
// DO NOT EDIT!


#ifndef PYROBOT_BRIDGE_MESSAGE_FKCOMMANDRESPONSE_H
#define PYROBOT_BRIDGE_MESSAGE_FKCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pyrobot_bridge
{
template <class ContainerAllocator>
struct FkCommandResponse_
{
  typedef FkCommandResponse_<ContainerAllocator> Type;

  FkCommandResponse_()
    : success(false)
    , pos()
    , quat()  {
    }
  FkCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , pos(_alloc)
    , quat(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pos_type;
  _pos_type pos;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _quat_type;
  _quat_type quat;





  typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FkCommandResponse_

typedef ::pyrobot_bridge::FkCommandResponse_<std::allocator<void> > FkCommandResponse;

typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandResponse > FkCommandResponsePtr;
typedef boost::shared_ptr< ::pyrobot_bridge::FkCommandResponse const> FkCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pyrobot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'HasHeader': False, 'IsFixedSize': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e705f17fae9810c48f6e9058ab1bdfb7";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe705f17fae9810c4ULL;
  static const uint64_t static_value2 = 0x8f6e9058ab1bdfb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyrobot_bridge/FkCommandResponse";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
float64[] pos\n\
float64[] quat\n\
\n\
";
  }

  static const char* value(const ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.pos);
      stream.next(m.quat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FkCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyrobot_bridge::FkCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "quat[]" << std::endl;
    for (size_t i = 0; i < v.quat.size(); ++i)
    {
      s << indent << "  quat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.quat[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYROBOT_BRIDGE_MESSAGE_FKCOMMANDRESPONSE_H
