// Generated by gencpp from file pyrobot_bridge/FkCommand.msg
// DO NOT EDIT!


#ifndef PYROBOT_BRIDGE_MESSAGE_FKCOMMAND_H
#define PYROBOT_BRIDGE_MESSAGE_FKCOMMAND_H

#include <ros/service_traits.h>


#include <pyrobot_bridge/FkCommandRequest.h>
#include <pyrobot_bridge/FkCommandResponse.h>


namespace pyrobot_bridge
{

struct FkCommand
{

typedef FkCommandRequest Request;
typedef FkCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FkCommand
} // namespace pyrobot_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pyrobot_bridge::FkCommand > {
  static const char* value()
  {
    return "6a7a6cbcb17cacd9771eda9bb83c64a6";
  }

  static const char* value(const ::pyrobot_bridge::FkCommand&) { return value(); }
};

template<>
struct DataType< ::pyrobot_bridge::FkCommand > {
  static const char* value()
  {
    return "pyrobot_bridge/FkCommand";
  }

  static const char* value(const ::pyrobot_bridge::FkCommand&) { return value(); }
};


// service_traits::MD5Sum< ::pyrobot_bridge::FkCommandRequest> should match 
// service_traits::MD5Sum< ::pyrobot_bridge::FkCommand > 
template<>
struct MD5Sum< ::pyrobot_bridge::FkCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pyrobot_bridge::FkCommand >::value();
  }
  static const char* value(const ::pyrobot_bridge::FkCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pyrobot_bridge::FkCommandRequest> should match 
// service_traits::DataType< ::pyrobot_bridge::FkCommand > 
template<>
struct DataType< ::pyrobot_bridge::FkCommandRequest>
{
  static const char* value()
  {
    return DataType< ::pyrobot_bridge::FkCommand >::value();
  }
  static const char* value(const ::pyrobot_bridge::FkCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pyrobot_bridge::FkCommandResponse> should match 
// service_traits::MD5Sum< ::pyrobot_bridge::FkCommand > 
template<>
struct MD5Sum< ::pyrobot_bridge::FkCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pyrobot_bridge::FkCommand >::value();
  }
  static const char* value(const ::pyrobot_bridge::FkCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pyrobot_bridge::FkCommandResponse> should match 
// service_traits::DataType< ::pyrobot_bridge::FkCommand > 
template<>
struct DataType< ::pyrobot_bridge::FkCommandResponse>
{
  static const char* value()
  {
    return DataType< ::pyrobot_bridge::FkCommand >::value();
  }
  static const char* value(const ::pyrobot_bridge::FkCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PYROBOT_BRIDGE_MESSAGE_FKCOMMAND_H
