// Generated by gencpp from file pyrobot_bridge/IkCommandResponse.msg
// DO NOT EDIT!


#ifndef PYROBOT_BRIDGE_MESSAGE_IKCOMMANDRESPONSE_H
#define PYROBOT_BRIDGE_MESSAGE_IKCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pyrobot_bridge
{
template <class ContainerAllocator>
struct IkCommandResponse_
{
  typedef IkCommandResponse_<ContainerAllocator> Type;

  IkCommandResponse_()
    : success(false)
    , joint_positions()  {
    }
  IkCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , joint_positions(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_positions_type;
  _joint_positions_type joint_positions;





  typedef boost::shared_ptr< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IkCommandResponse_

typedef ::pyrobot_bridge::IkCommandResponse_<std::allocator<void> > IkCommandResponse;

typedef boost::shared_ptr< ::pyrobot_bridge::IkCommandResponse > IkCommandResponsePtr;
typedef boost::shared_ptr< ::pyrobot_bridge::IkCommandResponse const> IkCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pyrobot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'HasHeader': False, 'IsFixedSize': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95136edf259d6766d754d1fdf3054d2c";
  }

  static const char* value(const ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95136edf259d6766ULL;
  static const uint64_t static_value2 = 0xd754d1fdf3054d2cULL;
};

template<class ContainerAllocator>
struct DataType< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyrobot_bridge/IkCommandResponse";
  }

  static const char* value(const ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
float64[] joint_positions\n\
\n\
";
  }

  static const char* value(const ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.joint_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyrobot_bridge::IkCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYROBOT_BRIDGE_MESSAGE_IKCOMMANDRESPONSE_H
